name: build
on: [push, pull_request]

jobs:
  run:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
            #- macos-latest
        ocaml-compiler:
          - 4.08.x
          - 4.12.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - run: opam pin -n .
    - run: opam depext -yt tracy tracy-client
    - run: opam install . -t --deps-only
    - run: opam exec -- dune build @install
